controller_manager:  
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


forward_position_controller:
  ros__parameters:
    joints:
      - jaw_1
      - jaw_2
      - roll
      - pitch
    interface_name: position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - jaw_1
      - jaw_2
      - roll
      - pitch
    command_interfaces:
      - position
    state_interfaces:
      - position
    # state_publish_rate: 200.0
    # action_monitor_rate: 20.0

    # allow_partial_joints_goal: false
    # open_loop_control: true
    # allow_integration_in_goal_trajectories: true
    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 0.0 # start immediately