controller_manager:  
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


forward_position_controller:
  ros__parameters:
    joints:
      - jaw_1
      - jaw_2
      - roll
      - pitch
    interface_name: position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - jaw_1
      - jaw_2
      - roll
      - pitch
    command_interfaces:
      - position
    state_interfaces:
      - position